---
- name: Install Redis
  hosts: redis
  become: true

  vars:
    redis_port: 6379
    redis_bind_interface: 0.0.0.0
    redis_requirepass: "{{ redis_password }}"
    redis_disabled_commands:
      - FLUSHDB
      - FLUSHALL
      - KEYS
      - PEXPIRE
      - DEL
      - CONFIG
      - SHUTDOWN

  roles:
    - role: geerlingguy.redis
